repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: npm-lint
        name: Run NPM Lint in vue-components
        files: ^vue-components/*
        entry: sh -c 'cd vue-components && npm run lint'
        language: system
